name: Builds

on:
  push:
    branches: [ main ]

# Declare default permissions as read only.
permissions: read-all

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v3
      -
        name: Install nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 18
      -
        name: Build code
        run: |
          npm install
          npm run build
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/quickref:app-${{ github.run_number }}
            ${{ secrets.DOCKERHUB_USERNAME }}/quickref:latest
  modifymanifest:
    name: Modify Manifest
    needs: build
    runs-on: ubuntu-latest
    steps:
      -
        name: Changing the deployment of git repo
        uses: actions/checkout@v3
        with:
          repository: 'ChauVinhAn/quickref_helmchart'
          token: ${{ secrets.GIT_PASSWORD }}
      -
        name: Modify metadata
        run: |
          git config user.email chauvinhan@gmail.com
          git config user.name ChauVinhAn
          pwd
          cat deployment.yaml
          pwd
          yq e '.metadata.name = "quickref-deployment-${{ github.run_number }}"' -i deployment.yaml
          cat deployment.yaml
          git add .
          git commit -m 'Done  by Github Actions   Job changemanifest: ${{ github.run_number }}'
          git push origin main
        env:
          GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
          GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}